services:
  app:
    build: .
    restart: always
    depends_on:
      - redis
    stop_grace_period: 0s
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
      - GAME_LINKS_FILE=data/links.txt

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  caddy:
    image: caddy:2-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./web:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8080:8080"

volumes:
  redis_data:
  caddy_data:
  caddy_config:
